var countries = new Object();
countries = [
{"flag": "AF.svg", label: "Afghanistan"},
{"flag": "AX.svg", label: "\u00c5land Islands"},
{"flag": "AL.svg", label: "Albania"},
{"flag": "DZ.svg", label: "Algeria"},
{"flag": "AS.svg", label: "American Samoa"},
{"flag": "AD.svg", label: "Andorra"},
{"flag": "AO.svg", label: "Angola"},
{"flag": "AI.svg", label: "Anguilla"},
{"flag": "AQ.svg", label: "Antarctica"},
{"flag": "AG.svg", label: "Antigua and Barbuda"},
{"flag": "AR.svg", label: "Argentina"},
{"flag": "AM.svg", label: "Armenia"},
{"flag": "AW.svg", label: "Aruba"},
{"flag": "AU.svg", label: "Australia"},
{"flag": "AT.svg", label: "Austria"},
{"flag": "AZ.svg", label: "Azerbaijan"},
{"flag": "BS.svg", label: "Bahamas"},
{"flag": "BH.svg", label: "Bahrain"},
{"flag": "BD.svg", label: "Bangladesh"},
{"flag": "BB.svg", label: "Barbados"},
{"flag": "BY.svg", label: "Belarus"},
{"flag": "BE.svg", label: "Belgium"},
{"flag": "BZ.svg", label: "Belize"},
{"flag": "BJ.svg", label: "Benin"},
{"flag": "BM.svg", label: "Bermuda"},
{"flag": "BT.svg", label: "Bhutan"},
{"flag": "BO.svg", label: "Bolivia, Plurinational State of"},
{"flag": "BQ.svg", label: "Bonaire, Sint Eustatius and Saba"},
{"flag": "BA.svg", label: "Bosnia and Herzegovina"},
{"flag": "BW.svg", label: "Botswana"},
{"flag": "BV.svg", label: "Bouvet Island"},
{"flag": "BR.svg", label: "Brazil"},
{"flag": "IO.svg", label: "British Indian Ocean Territory"},
{"flag": "BN.svg", label: "Brunei Darussalam"},
{"flag": "BG.svg", label: "Bulgaria"},
{"flag": "BF.svg", label: "Burkina Faso"},
{"flag": "BI.svg", label: "Burundi"},
{"flag": "KH.svg", label: "Cambodia"},
{"flag": "CM.svg", label: "Cameroon"},
{"flag": "CA.svg", label: "Canada"},
{"flag": "CV.svg", label: "Cape Verde"},
{"flag": "KY.svg", label: "Cayman Islands"},
{"flag": "CF.svg", label: "Central African Republic"},
{"flag": "TD.svg", label: "Chad"},
{"flag": "CL.svg", label: "Chile"},
{"flag": "CN.svg", label: "China"},
{"flag": "CX.svg", label: "Christmas Island"},
{"flag": "CC.svg", label: "Cocos (Keeling) Islands"},
{"flag": "CO.svg", label: "Colombia"},
{"flag": "KM.svg", label: "Comoros"},
{"flag": "CG.svg", label: "Congo"},
{"flag": "CD.svg", label: "Congo, the Democratic Republic of the"},
{"flag": "CK.svg", label: "Cook Islands"},
{"flag": "CR.svg", label: "Costa Rica"},
{"flag": "CI.svg", label: "C\u00f4te d'Ivoire"},
{"flag": "HR.svg", label: "Croatia"},
{"flag": "CU.svg", label: "Cuba"},
{"flag": "CW.svg", label: "Cura\u00e7ao"},
{"flag": "CY.svg", label: "Cyprus"},
{"flag": "CZ.svg", label: "Czech Republic"},
{"flag": "DK.svg", label: "Denmark"},
{"flag": "DJ.svg", label: "Djibouti"},
{"flag": "DM.svg", label: "Dominica"},
{"flag": "DO.svg", label: "Dominican Republic"},
{"flag": "EC.svg", label: "Ecuador"},
{"flag": "EG.svg", label: "Egypt"},
{"flag": "SV.svg", label: "El Salvador"},
{"flag": "GQ.svg", label: "Equatorial Guinea"},
{"flag": "ER.svg", label: "Eritrea"},
{"flag": "EE.svg", label: "Estonia"},
{"flag": "ET.svg", label: "Ethiopia"},
{"flag": "FK.svg", label: "Falkland Islands (Malvinas)"},
{"flag": "FO.svg", label: "Faroe Islands"},
{"flag": "FJ.svg", label: "Fiji"},
{"flag": "FI.svg", label: "Finland"},
{"flag": "FR.svg", label: "France"},
{"flag": "GF.svg", label: "French Guiana"},
{"flag": "PF.svg", label: "French Polynesia"},
{"flag": "TF.svg", label: "French Southern Territories"},
{"flag": "GA.svg", label: "Gabon"},
{"flag": "GM.svg", label: "Gambia"},
{"flag": "GE.svg", label: "Georgia"},
{"flag": "DE.svg", label: "Germany"},
{"flag": "GH.svg", label: "Ghana"},
{"flag": "GI.svg", label: "Gibraltar"},
{"flag": "GR.svg", label: "Greece"},
{"flag": "GL.svg", label: "Greenland"},
{"flag": "GD.svg", label: "Grenada"},
{"flag": "GP.svg", label: "Guadeloupe"},
{"flag": "GU.svg", label: "Guam"},
{"flag": "GT.svg", label: "Guatemala"},
{"flag": "GG.svg", label: "Guernsey"},
{"flag": "GN.svg", label: "Guinea"},
{"flag": "GW.svg", label: "Guinea-Bissau"},
{"flag": "GY.svg", label: "Guyana"},
{"flag": "HT.svg", label: "Haiti"},
{"flag": "HM.svg", label: "Heard Island and McDonald Islands"},
{"flag": "VA.svg", label: "Holy See (Vatican City State)"},
{"flag": "HN.svg", label: "Honduras"},
{"flag": "HK.svg", label: "Hong Kong"},
{"flag": "HU.svg", label: "Hungary"},
{"flag": "IS.svg", label: "Iceland"},
{"flag": "IN.svg", label: "India"},
{"flag": "ID.svg", label: "Indonesia"},
{"flag": "IR.svg", label: "Iran, Islamic Republic of"},
{"flag": "IQ.svg", label: "Iraq"},
{"flag": "IE.svg", label: "Ireland"},
{"flag": "IM.svg", label: "Isle of Man"},
{"flag": "IL.svg", label: "Israel"},
{"flag": "IT.svg", label: "Italy"},
{"flag": "JM.svg", label: "Jamaica"},
{"flag": "JP.svg", label: "Japan"},
{"flag": "JE.svg", label: "Jersey"},
{"flag": "JO.svg", label: "Jordan"},
{"flag": "KZ.svg", label: "Kazakhstan"},
{"flag": "KE.svg", label: "Kenya"},
{"flag": "KI.svg", label: "Kiribati"},
{"flag": "KP.svg", label: "Korea, Democratic People's Republic of"},
{"flag": "KR.svg", label: "Korea, Republic of"},
{"flag": "KW.svg", label: "Kuwait"},
{"flag": "KG.svg", label: "Kyrgyzstan"},
{"flag": "LA.svg", label: "Lao People's Democratic Republic"},
{"flag": "LV.svg", label: "Latvia"},
{"flag": "LB.svg", label: "Lebanon"},
{"flag": "LS.svg", label: "Lesotho"},
{"flag": "LR.svg", label: "Liberia"},
{"flag": "LY.svg", label: "Libya"},
{"flag": "LI.svg", label: "Liechtenstein"},
{"flag": "LT.svg", label: "Lithuania"},
{"flag": "LU.svg", label: "Luxembourg"},
{"flag": "MO.svg", label: "Macao"},
{"flag": "MK.svg", label: "Macedonia, the Former Yugoslav Republic of"},
{"flag": "MG.svg", label: "Madagascar"},{"flag": "MW", label: "Malawi"},
{"flag": "MY.svg", label: "Malaysia"},{"flag": "MV", label: "Maldives"},
{"flag": "ML.svg", label: "Mali"},{"flag": "MT", label: "Malta"},
{"flag": "MH.svg", label: "Marshall Islands"},
{"flag": "MQ.svg", label: "Martinique"},
{"flag": "MR.svg", label: "Mauritania"},
{"flag": "MU.svg", label: "Mauritius"},
{"flag": "YT.svg", label: "Mayotte"},
{"flag": "MX.svg", label: "Mexico"},
{"flag": "FM.svg", label: "Micronesia, Federated States of"},
{"flag": "MD.svg", label: "Moldova, Republic of"},
{"flag": "MC.svg", label: "Monaco"},
{"flag": "MN.svg", label: "Mongolia"},
{"flag": "ME.svg", label: "Montenegro"},
{"flag": "MS.svg", label: "Montserrat"},
{"flag": "MA.svg", label: "Morocco"},
{"flag": "MZ.svg", label: "Mozambique"},
{"flag": "MM.svg", label: "Myanmar"},
{"flag": "NA.svg", label: "Namibia"},
{"flag": "NR.svg", label: "Nauru"},
{"flag": "NP.svg", label: "Nepal"},
{"flag": "NL.svg", label: "Netherlands"},
{"flag": "NC.svg", label: "New Caledonia"},
{"flag": "NZ.svg", label: "New Zealand"},
{"flag": "NI.svg", label: "Nicaragua"},
{"flag": "NE.svg", label: "Niger"},
{"flag": "NG.svg", label: "Nigeria"},
{"flag": "NU.svg", label: "Niue"},
{"flag": "NF.svg", label: "Norfolk Island"},
{"flag": "MP.svg", label: "Northern Mariana Islands"},
{"flag": "NO.svg", label: "Norway"},
{"flag": "OM.svg", label: "Oman"},
{"flag": "PK.svg", label: "Pakistan"},
{"flag": "PW.svg", label: "Palau"},
{"flag": "PS.svg", label: "Palestine, State of"},
{"flag": "PA.svg", label: "Panama"},
{"flag": "PG.svg", label: "Papua New Guinea"},
{"flag": "PY.svg", label: "Paraguay"},
{"flag": "PE.svg", label: "Peru"},
{"flag": "PH.svg", label: "Philippines"},
{"flag": "PN.svg", label: "Pitcairn"},
{"flag": "PL.svg", label: "Poland"},
{"flag": "PT.svg", label: "Portugal"},
{"flag": "PR.svg", label: "Puerto Rico"},
{"flag": "QA.svg", label: "Qatar"},
{"flag": "RE.svg", label: "R\u00e9union"},
{"flag": "RO.svg", label: "Romania"},
{"flag": "RU.svg", label: "Russian Federation"},
{"flag": "RW.svg", label: "Rwanda"},
{"flag": "BL.svg", label: "Saint Barth\u00e9lemy"},
{"flag": "SH.svg", label: "Saint Helena, Ascension and Tristan da Cunha"},
{"flag": "KN.svg", label: "Saint Kitts and Nevis"},
{"flag": "LC.svg", label: "Saint Lucia"},
{"flag": "MF.svg", label: "Saint Martin (French part)"},{"flag": "PM", label: "Saint Pierre and Miquelon"},
{"flag": "VC.svg", label: "Saint Vincent and the Grenadines"},
{"flag": "WS.svg", label: "Samoa"},
{"flag": "SM.svg", label: "San Marino"},
{"flag": "ST.svg", label: "Sao Tome and Principe"},
{"flag": "SA.svg", label: "Saudi Arabia"},
{"flag": "SN.svg", label: "Senegal"},
{"flag": "RS.svg", label: "Serbia"},
{"flag": "SC.svg", label: "Seychelles"},
{"flag": "SL.svg", label: "Sierra Leone"},
{"flag": "SG.svg", label: "Singapore"},
{"flag": "SX.svg", label: "Sint Maarten (Dutch part)"},
{"flag": "SK.svg", label: "Slovakia"},
{"flag": "SI.svg", label: "Slovenia"},
{"flag": "SB.svg", label: "Solomon Islands"},
{"flag": "SO.svg", label: "Somalia"},
{"flag": "ZA.svg", label: "South Africa"},
{"flag": "GS.svg", label: "South Georgia and the South Sandwich Islands"},
{"flag": "SS.svg", label: "South Sudan"},
{"flag": "ES.svg", label: "Spain"},
{"flag": "LK.svg", label: "Sri Lanka"},
{"flag": "SD.svg", label: "Sudan"},
{"flag": "SR.svg", label: "Suriname"},
{"flag": "SJ.svg", label: "Svalbard and Jan Mayen"},
{"flag": "SZ.svg", label: "Swaziland"},
{"flag": "SE.svg", label: "Sweden"},
{"flag": "CH.svg", label: "Switzerland"},
{"flag": "SY.svg", label: "Syrian Arab Republic"},
{"flag": "TW.svg", label: "Taiwan, Province of China"},
{"flag": "TJ.svg", label: "Tajikistan"},
{"flag": "TZ.svg", label: "Tanzania, United Republic of"},
{"flag": "TH.svg", label: "Thailand"},
{"flag": "TL.svg", label: "Timor-Leste"},
{"flag": "TG.svg", label: "Togo"},
{"flag": "TK.svg", label: "Tokelau"},
{"flag": "TO.svg", label: "Tonga"},
{"flag": "TT.svg", label: "Trinidad and Tobago"},
{"flag": "TN.svg", label: "Tunisia"},
{"flag": "TR.svg", label: "Turkey"},
{"flag": "TM.svg", label: "Turkmenistan"},
{"flag": "TC.svg", label: "Turks and Caicos Islands"},
{"flag": "TV.svg", label: "Tuvalu"},
{"flag": "UG.svg", label: "Uganda"},
{"flag": "UA.svg", label: "Ukraine"},
{"flag": "AE.svg", label: "United Arab Emirates"},
{"flag": "GB.svg", label: "United Kingdom"},
{"flag": "US.svg", label: "United States"},
{"flag": "UM.svg", label: "United States Minor Outlying Islands"},
{"flag": "UY.svg", label: "Uruguay"},
{"flag": "UZ.svg", label: "Uzbekistan"},
{"flag": "VU.svg", label: "Vanuatu"},
{"flag": "VE.svg", label: "Venezuela, Bolivarian Republic of"},
{"flag": "VN.svg", label: "Viet Nam"},
{"flag": "VG.svg", label: "Virgin Islands, British"},
{"flag": "VI.svg", label: "Virgin Islands, U.S."},
{"flag": "WF.svg", label: "Wallis and Futuna"},
{"flag": "EH.svg", label: "Western Sahara"},
{"flag": "YE.svg", label: "Yemen"},
{"flag": "ZM.svg", label: "Zambia"},
{"flag": "ZW.svg", label: "Zimbabwe"}];
